[package]
name = "ra8876-registers"
version = "0.0.1"
license = "MIT OR Apache-2.0"
repository = "https://github.com/cstrahan/ra8876-rs.git"
description = "A register access layer for the RA8876 LCD controller"
edition = "2021"
